// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "9usINaOrli6C9wqZIK23OFAllRs4eLqnnq4fu39pn0I6dQVzJfy9Gha7VfMabbMeSbqbCw";
}
}
}

